[package]
name = "aptabase-rs"
version = "0.1.0"
authors = ["Eugén Cowie"]
edition = "2024"
description = "Rust SDK for Aptabase: Open Source, Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps"
homepage = "https://github.com/eugencowie/aptabase-rs"
repository = "https://github.com/eugencowie/aptabase-rs"
license = "MIT"
keywords = ["analytics", "aptabase", "telemetry"]
categories = ["api-bindings"]

[dependencies]
tokio = "1.43.0"
futures = "0.3.31"
serde = "1.0.217"
serde_json = "1.0.138"
reqwest = { version = "0.12.12", features = ["json"] }
time = { version = "0.3.37", features = ["formatting"] }
os_info = "3.9.2"
rand = "0.9.0"
log = "0.4.25"
sys-locale = "0.3.2"

[lints.rust]
warnings = "deny"

[lints.clippy]
all = "deny"

[workspace.metadata.git-cliff.changelog]
output = "CHANGELOG.md"
header = "# Changelog"
body = """

{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }}
{% else %}\
    ## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}**BREAKING CHANGE**: {% endif %}\
            {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}
"""
postprocessors = [
    { pattern = "\\(#([0-9]+)\\)", replace = "([#${1}](https://github.com/eugencowie/aptabase-rs/pull/${1}))" },
]

[workspace.metadata.git-cliff.git]
filter_commits = true
commit_parsers = [
    { message = "^feat: .+ \\(#[0-9]+\\)", group = "<!-- 0 -->🚀 Features" },
    { message = "^fix: .+ \\(#[0-9]+\\)", group = "<!-- 1 -->🐛 Bug Fixes" },
    { message = "^docs?: .+ \\(#[0-9]+\\)", group = "<!-- 3 -->📚 Documentation" },
    { message = "^perf: .+ \\(#[0-9]+\\)", group = "<!-- 4 -->⚡ Performance" },
    { message = "^refactor: .+ \\(#[0-9]+\\)", group = "<!-- 2 -->🚜 Refactor" },
    { message = "^style: .+ \\(#[0-9]+\\)", group = "<!-- 5 -->🎨 Styling" },
    { message = "^test: .+ \\(#[0-9]+\\)", group = "<!-- 6 -->🧪 Testing" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps.*\\)", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^(chore|ci): .+ \\(#[0-9]+\\)", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
    { message = "^[a-z]+: .+ \\(#[0-9]+\\)", body = ".*security", group = "<!-- 8 -->🛡️ Security" },
    { message = "^revert: .+ \\(#[0-9]+\\)", group = "<!-- 9 -->◀️ Revert" },
]
