[package]
name = "aptabase-rs"
version = "0.3.0"
authors = ["Eugén Cowie"]
edition = "2021"
resolver = "3"
description = "Rust SDK for Aptabase: Open Source, Privacy-First and Simple Analytics for Mobile, Desktop and Web Apps"
homepage = "https://github.com/eugencowie/aptabase-rs"
repository = "https://github.com/eugencowie/aptabase-rs"
license = "MIT"
keywords = ["analytics", "aptabase", "telemetry"]
categories = ["api-bindings"]

[dependencies]
tokio = "1.43.0"
futures = "0.3.31"
serde = "1.0.217"
serde_json = "1.0.138"
reqwest = { version = "0.13.4", default-features = false, features = ["json", "charset", "http2", "system-proxy"] }
time = { version = "0.3.37", features = ["formatting"] }
os_info = "3.9.2"
rand = "0.10.0"
log = "0.4.25"
sys-locale = "0.3.2"

[features]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
native-tls = ["reqwest/native-tls"]
rustls-tls = ["reqwest/rustls"]

[lints.rust]
warnings = "deny"

[lints.clippy]
all = "deny"
