[tools]
actionlint = "latest"
gh = "latest"
git-cliff = "latest"
node = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:skills" = "latest"
release-plz = "latest"
rust = "stable"

[tasks.init]
description = "Initialise development environment"
run = [
  "skills experimental_install",
  "cp -r .agents/. .claude",
  "echo @AGENTS.md > CLAUDE.md"
]

[tasks.test]
description = "Run tests"
run = "cargo test"

[tasks.format]
description = "Fix formatting issues"
run = "cargo fmt"

[tasks.lint]
description = "Fix linting issues"
run = "cargo clippy --all-targets --fix --allow-dirty"

[tasks.check]
description = "Check formatting/linting/tests"
run = [
  "cargo fmt --check",
  "cargo clippy --all-targets",
  "cargo test"
]

[tasks.changelog]
description = "Update changelog"
run = "git cliff --bump"

[tasks.release]
description = "Perform release process locally"
run = "release-plz update"
